# Generated by Django 5.0.1 on 2024-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, unique=True)),
                ('ISBN_No', models.IntegerField(unique=True)),
                ('author_name', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('year_of_publication', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
